[tool.poetry]
name = "impossible-inherent-entropy"
version = "0.1.0"
description = ""
authors = ["agiats"]
readme = "README.md"
include = ["src"]

[tool.poetry.dependencies]
python = "^3.10"
tqdm = "^4.66.6"
frozendict = "^2.4.6"
rayuela = {git = "git@github.com:rycolab/rayuela.git", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
