[tool.poetry]
name = "rau"
version = "0.1.0"
description = "Machine translation, language modeling, etc. in PyTorch."
authors = ["Brian DuSell <bdusell@inf.ethz.ch>"]

[tool.poetry.dependencies]
python = "^3.11"
beautifulsoup4 = "^4.12.2"
humanfriendly = "^10.0"
more-itertools = "^10.1.0"
torch = "^2.1.0"

[tool.poetry.dev-dependencies]
mypy = "^1.7.1"
pytest = "^7.4.3"
sphinx = "^7.2.6"
sphinx-autodoc-typehints = "^1.25.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
